drone_inventory/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate 
import uuid 
from datetime import datetime 


# Adding Flask Security for passwords
from werkzeug.security import generate_password_hash, check_password_hash

# Import Secrets Module
import secrets

# Import for LoginManager & UserMixin
# help us login our users & store their credentials
from flask_login import UserMixin, LoginManager

#import for Flask-Marshmallow
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    first_name = db.Column(db.String(150), nullable = True, default = '')
    last_name = db.Column(db.String(150), nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = False, default = '')
    username = db.Column(db.String, nullable = False)
    token = db.Column(db.String, default = '', unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    # create relationship between User table & Drone table 

    def __init__(self, email, username, password, first_name = '', last_name = ''):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token()
        self.username = username


    def set_id(self):
        return str(uuid.uuid4())
    
    def set_password(self, password):
        return generate_password_hash(password)
    
    def set_token(self):
        return secrets.token_hex(24)
    

    def __repr__(self):
        return f"User {self.email} has been added to the database! Woohoo!"
    

class Drone(db.model):
    id = db.Column(db.String, primary_key = True)
    name = db.Column(db.String(150))
    description = db.Column(db.String(200), nullable = True)
    price = db.column(db.Numeric(precision=10, scale=2))
    camera_quality = db.Column(db.String(150), nullable=True)
    flight_time = db.Column(db.String(100), nullable=True)
    max_speed = db.column(db.String(100))
    dimension = db.Column(db.String(100))
    weight = db.Column(db.String(100))
    cost_of_producton = db.Column(db.Number(presision=10, scale=2))
    series = db.Column(db.String(150))
    random_joke = db.Column(db.String, nullable=True)
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, name, description, price, camera_quality, flight_time, max_speed, dimension, weight,
                 cost_of_producton, series, random_joke, user_token):
        self.id = self.set.id()
        self.name = name
        self.description = description
        self.price = price
        self.camera_quality = camera_quality
        self.flight_time = flight_time
        self.max_speed = max_speed
        self.dimensions = dimension
        self.weight = weight
        self.cost_of_producton = cost_of_producton
        self.series = series
        self.random_joke = random_joke
        self.user_token =user_token

    def set_id():
        return str(uuid.uuid4())

drone_inventory/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):
    username = StringField('username', validators = [DataRequired()])
    email = StringField('email', validators = [DataRequired(), Email()])
    password = PasswordField('password', validators = [DataRequired()])
    submit_button = SubmitField()

drone_inventory/__init__.py
from flask import Flask 
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .models import db as root_db

from flask_migrate import Migrate

# Flask CORS import - Cross Origin Resource Sharing
# future proofing fr our react app to be able to access our flask api
from flask_cors import CORS

app = Flask(__name__)

# @app.route("/") #simple route on the homepage
# def hello_world():
    # return "<p>Hello, World!</p>"

app.register_blueprint(site)
app.register_blueprint(auth)

app.config.from_object(Config)

root_db.init_app(app)
migrate = Migrate(app, root_db)

CORS(app)

drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from drone_inventory.forms import UserLoginForm
from flask import request
from drone_inventory.models import User, db

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    userform = UserLoginForm()

    try:
        if request.method == 'POST' and userform.validate_on_submit():
            email = userform.email.data
            username = userform.username.data
            password = userform.password.data
            print(email, password)

            user = User(email, username, password)

            db.session.add(user)
            db.session.commit()
    
            flash(f'You have successfully created a user account {email}', 'user-created')
            
            return redirect(url_for('site.home'))

         
    except:
        raise Exception('Invalid Form Data. Please Check your form')
    
    return render_template('signup.html', form=userform)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    return render_template('signin.html')

    

drone_inventory/site/routes.py
from flask import Blueprint, render_template 


site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
def home():
    print('look at this cool project. Would you just look at it')
    return render_template('index.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Drone Inventory API</title>
</head>
<body>

        <!-- NavBar Here -->
        <nav class="ct-nav">
            <div>
                <img src="../static/images/CARSLOGO.png" alt="Coding Drones Logo">
            </div>

            <div>
                <ul id="horizontal-list">
                    <a href="{{ url_for('site.home') }}">
                        <li style="color: white;">The Coding Drones Project</li>
                    </a>
                    <a href="{{ url_for('site.home') }}">
                        <li style="color: white;">Home</li>
                    </a>
                    <a href="#">
                        <li style="color: white;">Profile</li>
                    </a>
                    <a href="#">
                        <li style="color: white;">Log Out</li>
                    </a>
                    <a href="{{ url_for('auth.signin') }}">
                        <li style="color: white;">Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li style="color: red;">Sign Up</li>
                    </a>
                </ul>
            </div>            
        </nav>

        <!-- End Nav Bar -->

        {% block content %}
        {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/forms.html
<!-- HTML produced & used by our Flask Form -->

<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class='form-control', placeholder = "Place Username Here...")}}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class='form-control', placeholder = "Place Password Here...")}}
        </fieldset>

        <!-- Submit Button Field -->
        {{ form.submit_button(class='btn btn-primary btn-block')}}
    </div>
</form>